version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SQL_SERVER_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - ./SqlServer_localVolumes/data:/var/opt/mssql/data
      - ./SqlServer_localVolumes/log:/var/opt/mssql/log
      - ./SqlServer_localVolumes/secrets:/var/opt/mssql/secrets
        
